### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by frankier** [ranjanan/MonteCarloIntegration.jl#19]
Hi @ranjanan! Would it be possible to make a new release?

**Comment by ranjanan** [comment]
Sure

**Comment by frankier** [comment]
Hi! It looks like it failed https://github.com/JuliaRegistries/General/pull/94651 because 0.2.0 was never released

**Comment by frankier** [comment]
@ranjanan Might you be able to fix this?

**Comment by ranjanan** [comment]
Sorry about the long turnaround here. I finally tagged a release.
